### ISSUE TITLE
Designs for Take a Class and generic content

### ISSUE THREAD

**Issue by jenkack** [labopm/website#13]

**Comment by humancompanion** [comment]
@timtimtimtimofficial delivered the design, I built those pages over the last few days. Please review and see my questions aroub custom offerings and design partnerships in issue #9

**Comment by jenkack** [comment]
@timtimtimtimofficial @humancompanion Any reason not to link the course name instead of Learn more?

https://federalist-proxy.app.cloud.gov/site/labopm/website/take-a-class/open-enrollment-classes/

**Comment by jenkack** [comment]
Probably nit-picky: change "Back to Open Enrollment Classes" to "More Open Enrollment Classes" in case user didn't come in from open enrollment index?

**Comment by humancompanion** [comment]
Oh yes. Duh. I should have caught that. Will make the course names links
and drop the extra column. Making the content actionable is a great design
principle to follow.
