### ISSUE TITLE
Section landing pages

### ISSUE THREAD

**Issue by jenkack** [labopm/website#19]
Is there a need to have the landing page content appear on subpages for each section, rather than a landing page directly from the section name? For example: on What We Do, could the Overview content display when clicking on What We Do, rather than What We Do > Overview? 

Same with Take a Class > Introduction
About The Lab > Cornerstones

**Comment by humancompanion** [comment]
Yes, there is a reason for how it is currently: The header component we're currently using from the USWDS uses the section name to trigger the opening of the menu. Thus it can't be a navigation element. 

We discussed going to the nav bar with secondary nav bar that @timtimtimtimofficial is depicting in his mock-ups however: What to do on mobile? usajobs.gov uses a similar pattern however, the secondary nav items are all one word and thus fit at 375px mobile with. That is not the case with our navigation. Thus it would mean a custom navigation pattern. I'm not against doing that but, only once everything else is done. Changing the Intro pages to index pages is a simple change.

**Comment by jenkack** [comment]
It's coming back to me. Thanks for explaining!
