### ISSUE TITLE
Establish google maps on locations page

### ISSUE THREAD

**Issue by humancompanion** [labopm/website#2]
The locations page calls for a google map image for each Lab location (DC, NY, SF, Boston). Some questions:

1. @seanmbaker - Are we allowed to use Javascript on our site?
2. Jen or @janesays - Was the intent for these to be images or actual maps?

If the intent was for these to just be images then, Jen, could you screenshot a google map for each location and drop the images in this issue for me? That would be quite helpful. Thanks.

**Comment by seanmbaker** [comment]
@humancompanion Should I bring this question to OCIO?

**Comment by jenkack** [comment]
My assumption was these were to be images, not actual maps. @janesays Let me know if you disagree. @humancompanion Here are screengrabs, I can redo if you need specific dimensions.

![bost](https://user-images.githubusercontent.com/34725831/57260205-7a4df980-7017-11e9-8e5c-6d8536d2f829.png)
![dc](https://user-images.githubusercontent.com/34725831/57260206-7ae69000-7017-11e9-8bc7-456531091ead.png)
![ny](https://user-images.githubusercontent.com/34725831/57260207-7ae69000-7017-11e9-8b2b-2ad503199afe.png)
![sf](https://user-images.githubusercontent.com/34725831/57260209-7ae69000-7017-11e9-8378-5a33358d14d5.png)

**Comment by humancompanion** [comment]
The design of the locations page from @timtimtimtimofficial is sans-maps. There is just one big image which you can see here: https://federalist-proxy.app.cloud.gov/site/labopm/website/about/locations/

The key is forthcoming and, if JS is allowed, the ability to toggle between the 2017 and 2018 versions. If JS is not allowed we could combine the 2 images into one or just use 2018. 

Regardless, @jenkack - Can we close this issue or re-purpose it for the tasks above?
