### ISSUE TITLE
Locations page map key and versions

### ISSUE THREAD

**Issue by jenkack** [labopm/website#20]
The key to the image map on locations page is forthcoming and, if JS is allowed, the ability to toggle between the 2017 and 2018 versions. If JS is not allowed we could combine the 2 images into one or just use 2018.

**Comment by humancompanion** [comment]
I can't do the toggle without Javascript, which we have not added (outside of what is in the Standards to work the nav and footer) and which we don't have permission to use yet. 

@timtimtimtimofficial - Could we just combine the two images into one and call it a day?

**Comment by timtimtimtimofficial** [comment]
No prob. I think we should just show the 2018 map.

**Comment by humancompanion** [comment]
Then I'm closing this per Tim's decree.
