### ISSUE TITLE
Setup airtable form for those interested in joining The Lab

### ISSUE THREAD

**Issue by humancompanion** [labopm/website#3]
On the careers page we have a form for joining us. I believe the intent is for us to use airtable to receive the form data. But I'm a little unclear whether we intended for Airtable to present the form itself. I don't see an option to embed an airtable form in another page so that may be our only option. Hoping Jane can set us straight and create the form for us and I can just link to it.

This is what was in the content in regards to what we wanted collected:

* First Name
* What agency did they come from?
* What was their background before joining?
* What did they work on with us?
* How they applied their experience once their detail was done?

**Comment by jenkack** [comment]
@humancompanion @janesays Per Sean this page needs to be revisited... let's hold for the moment and I'll talk to Sean about this Friday.

**Comment by janenewman** [comment]
@humancompanion @jenkack Detailee interest form edit view is here: https://airtable.com/tbly2HTj8ieTUJ40k/viwYJI4hzUB1qky3Y?blocks=bipWj7HeYWfEi3cIt

The view for submissions is here:
https://airtable.com/shrClp00LFsPQOUm9

The form is in the people tab in lab calendar, contacts and codes

**Comment by jenkack** [comment]
@seanmbaker This is in the same bucket of questions for Heather Stern... like the Contact Us form question

**Comment by jenkack** [comment]
Noting here for now that at launch the Careers page can feature detail and rotation info, nothing for Open Opps or other open positions if nothing available

**Comment by humancompanion** [comment]
The form is setup and added to the page. Re-assigning to Sean to talk to Heather Stern.

**Comment by jenkack** [comment]
@humancompanion Sean had cleared the use of forms with Heather, I'm going to assign this to myself to get this page to completion, working with Sean.

**Comment by jenkack** [comment]
Closing this as Jane and I decided to remove the form for now. Can revisit.
