### ISSUE TITLE
What We Do > Partner with the Lab

### ISSUE THREAD

**Issue by jenkack** [labopm/website#32]
- [x] Sidebar for partner list
- [x] Jane recommends moving CTA spots for Contact us to a sidebar, perhaps a treatment like this: https://federalist-proxy.app.cloud.gov/site/labopm/website/class/fundamentals/ Would that work with the partner sidebar?
- [x] Rename page to Partner with us
- [x] Merge content from How we Work to this page
- [x] Remove How we Work page and nav

**Comment by timtimtimtimofficial** [comment]
Introduced some styling to help break up the content. Might still want to edit down a bit.

**Comment by jenkack** [comment]
@timtimtimtimofficial Looks good! I'm going to close this out for now and we can create a new issue for any feedback from Sean/Arianne to revisit the copy.
