### ISSUE TITLE
About the Lab > Cornerstones

### ISSUE THREAD

**Issue by jenkack** [labopm/website#34]
- [x] Change title to “Overview” in nav
- [x] Change title to “About the Lab” in the title banner
- [x] Change "How We Work" to "Our Approach"
- [x] Move up photo after the “Our vision” section, and consider a caption. Possibly move to Our History.
- [x] Specify warm & cool sidebar background styles in CSS

**Comment by jenkack** [comment]
@timtimtimtimofficial Do you want to make the call on the last item on this list?

**Comment by timtimtimtimofficial** [comment]
Added a little visual style update to the checklist.

**Comment by timtimtimtimofficial** [comment]
Moved photo off of this page and onto Our History. Fixed sidebar styles throughout the site.
