### ISSUE TITLE
Join the Lab: edit Details section

### ISSUE THREAD

**Issue by jenkack** [labopm/website#37]
- [x] Change title to “Join the Lab”
- [x] Edit down or restructure Details section
- [x] Confirm usage of form
- [x] Update Open Positions to remove Twitter language and provide short instruction on joining listerv

**Comment by jenkack** [comment]
It was decided to remove the detail AT form

**Comment by timtimtimtimofficial** [comment]
* Your edits condenses this section nicely! 
* In the second paragraph, "— as well as hosts" sounds a little funny to me, maybe could say:

> The Lab hosts details through several established programs, including Presidential Management Fellows, Executive Potential Program and the President’s Management Council Interagency Rotation Program. We also scope details directly with employees.
