### ISSUE TITLE
In the news: edit articles list

### ISSUE THREAD

**Issue by jenkack** [labopm/website#38]
Edit list of articles down to the best of them

To possibly add:
https://www.themandarin.com.au/89292-diis-design-academy-set-welcome-aps-staff/

**Comment by jenkack** [comment]
I found a note from Sean that says "Arianne still needs to provide me with Links of news articles"

I'll ask him about that!

**Comment by jenkack** [comment]
Sean will check with Arianne about additional articles/sources

**Comment by jenkack** [comment]
[news_new.txt](https://github.com/labopm/website/files/3454134/news_new.txt)
[news_old.txt](https://github.com/labopm/website/files/3454135/news_old.txt)

**Comment by timtimtimtimofficial** [comment]
* I like your rationale for culling/keeping articles. I think we could probably trim a couple more. Like maybe keep just the more recent USAJOBS article, and maybe remove one of the last two, which are both about USDA.
* That said, the page seems a little... barren? With just the single list. Maybe it's fine. I could see the page being rounded out by sharing a couple links to talks we've given, but the only one that I can find a recording of / anything written up is from a trip to Australia ([link](https://www.themandarin.com.au/89292-diis-design-academy-set-welcome-aps-staff/)) which could be too spicy for OPM Comms.
* There's also the option of adding a little "press area" with our logo, press contact, etc., but I don't really think we need that.
* Or it gets rolled up into "Our History"?
