### ISSUE TITLE
Form submissions results

### ISSUE THREAD

**Issue by jenkack** [labopm/website#43]
I tried testing out the Detail form and Contact Us form...

With Detail, when you submit, the response loads in the form area only, still displaying the rest of the surrounding page.

With Contact Us, when you submit, the response loads in the full page, none of the rest of the Contact Us page is visible and you need to use to navigate Back to get back to the site.

**Comment by humancompanion** [comment]
Hmm. I'm not sure how to control what Airtable does there. Thoughts @janesays?

**Comment by jenkack** [comment]
I talked to Jane about this... long story short we decided to remove the detail form from the Careers page, and move the Contact Us form to the "main" base from the other base it was in. I updated both pages with these changes and they'll be part of my next pull request, then will see if the form submission on Contact Us is still giving trouble..

From Jane:
Form for editing (needs more explanatory copy)
https://airtable.com/tbly2HTj8ieTUJ40k/viwEouqCXVm1nmisw?blocks=hide

Grab Embed code here:
https://airtable.com/shrnjxJT4oGlgaDca/embed

**Comment by jenkack** [comment]
When submitting contact us form, still getting a full page load of the reply instead of the form embed within the page. Once the latest pull request goes through, will try this code which removes the background color info, and is the only difference between the new contact us form code and what worked on the detail page.

<iframe class="airtable-embed" src="https://airtable.com/embed/shrnjxJT4oGlgaDca" frameborder="0" onmousewheel="" width="100%" height="1800px"></iframe>


<iframe class="airtable-embed" src="https://airtable.com/embed/shrnjxJT4oGlgaDca?backgroundColor=cyan" frameborder="0" onmousewheel="" width="100%" height="1800px"></iframe>
