### ISSUE TITLE
Embed video on News page

### ISSUE THREAD

**Issue by humancompanion** [labopm/website#5]
There was a call for a video about USAJOBS to be embedded on the News page. However, it's not a video we can actually embed. We *could* however embed our own Lab year in review video on the page given that it's posted on youtube. However, I need confirmation from @seanmbaker that we can use Javascript to do so. The original okay from OCIO for our use of Federalist included a stipulation that we not use any JS code. But I don't know if that's changed with the new CIO in place.

**Comment by seanmbaker** [comment]
Much of the Year in Review video content is already out dated and we do not have plans to do this again. We wont need it on our own site. Are you suggesting that the video on USAJOBS be embedded on lab.opm.gov or another place? You're right the new OCIO may be open to JS though. 

Where w

**Comment by jenkack** [comment]
@seanmbaker Your message above cut off... It sounds like the usajobs video is not embeddable, and if we're not using Year in Review then also sounds like no video on the page, which is fine IMO. 

(@seanmbaker Everything on this page is getting a bit stale, which also raises the question: Should we be focusing at some point on more press opps?)

**Comment by humancompanion** [comment]
Re-assigning to Sean because it is not clear what I should do here.

**Comment by jenkack** [comment]
Per Sean: Removing year in review entirely
