### ISSUE TITLE
Home page 

### ISSUE THREAD

**Issue by jenkack** [labopm/website#56]
I did a site walkthrough with Jane, and she has two recommendations for the home page:

- [x] Remove this graph and save it for somewhere else:
Driven by a spirit of collaboration across the federal workforce, we nurture the creative potential it takes for people to solve difficult and complex problems.

- [x] Remove the quotes for each of the "Let's..." She had envisioned rollovers to display the quotes, which is probably not doable without JS.

- ~~Reduce promo spots from four to three~~ _On second thought, I prefer (at least in desktop) the way the titles alternate left to right, left to right, and then return to left at "...together." I wouldn't want to start or end on a right-aligned prompt, so with just 3, you'd double-up on left-aligned prompts at the end._

- [x] Adjust spacing in CSS.

**Comment by timtimtimtimofficial** [comment]
Still a little bit of finessing to do with spacing, etc, but I pushed Jane's content removal suggestions.
