### ISSUE TITLE
Collect and/or create infographics

### ISSUE THREAD

**Issue by humancompanion** [labopm/website#6]
I'll compile a list of the images I need for the site. These are all in the content Word doc but, I'm collecting them here so I can track them.

* [x] Lab employees by year graphic - "a graphic here that shows the growth/makeup of the Lab" for the Our History page
* [x] ~~USDA graphic/system map for Awards page~~
* [x] ~~About the Lab - landing page - Design school photo~~
* [x] Where we've been graphic for Locations page - 2018
* [x] ~~Where we've been graphic for Location page - 2017~~
* [x] ~~Who we are graphic for the Our History page~~
* [x] ~~What we do - landing page - 4 icons~~

**Comment by timtimtimtimofficial** [comment]
Notes on the above:

- **"Where We've Been" maps** Updated the 2017 and 2018 maps and sent to Matt!
- **USDA graphic:** This graphic is a little outdated and 😬in its visual design, perhaps we can link to the PDF with a small thumbnail, or just a text link. Sent Matt the PDF and thumbnail. If there are no other awards we can claim, I think we should merge this page with "In the News."
- **Lab employees by year:** Working with Elaine on getting data. Leave out for now.
- **Who we are graphic:** This graphic looks cool, but merely differentiates between the various sources we hire from... I think it's too technical and doesn't really tell the story of "Our History." Could possibly repurpose visual format for something else, but leave out for now.
- **"Who we are" stats:** No data. And we will already (hopefully) have Lab team photos on that page anyway. Will revisit if we can't include Lab team photos. Leave out for now.

Notes on other pages:
- **What We Do - landing page:** 4 icons in progress
- **What We Do - Case Studies:** Work samples and imagery to come...
- **Take a Class - Custom:** Possibly IDS photo. Need to confirm photo consent form and make photo selection.
-**About the Lab - landing page:** Included a nice photo from Design School in the Lab space.

**Comment by humancompanion** [comment]
@timtimtimtimofficial - I'm getting CPT hand-off from Ben and Corinne tomorrow so I'm going to pause for a few days on this site in order to work on that one. However, realistically, if I don't have the remaining images by Thursday morning, I won't be able to get them in. Let me know if you want me to remove the placeholders that are there for some of the images.

**Comment by anatecture** [comment]
I can place the images next week, no worries.

**Comment by timtimtimtimofficial** [comment]
Concerning the placeholders on the "Our History" page -- I am happy to report I got the Lab "employees by year" data from Elaine today! I will work on that graphic, but won't likely be ready this week. However, I am confident we will be able to add it to the page after you go. 

On that same page, you can go ahead and remove the placeholder for the "Who We Are" graphic for the reasons I gave in a previous comment.

Concerning the other TBD images mentioned earlier...

- I mentioned we might want to add a photo from Immersive Design Studio to the "Custom Classes" landing page, but cancel that. I think the page looks good now that there's the table of offerings.
- The (now 3) potential icons I mentioned for the "What We Do" Overview page are still TBD. But I think we should just move forward with the layout as is.

**Comment by timtimtimtimofficial** [comment]
Updated the checklist above to reflect what's really left. I just still need to make the Lab-team-growth chart.

**Comment by timtimtimtimofficial** [comment]
Labbies-over-the-years graphic added. May change depending on Sean/Arianne feedback but I’ll close this issue.
