### ISSUE TITLE
Home page adjustments

### ISSUE THREAD

**Issue by jenkack** [labopm/website#68]
- [x] Tim: Get rid of the “…together” at the end, and instead put it in the block with “Do you have a complex challenge? <link>Partner with us</link>, and…” (then continue to the “Let’s ___” pieces). 

- [x] Jen: Take pass at rewriting 4 promo items, make one a custom class

**Comment by jenkack** [comment]
@timtimtimtimofficial Thoughts? Only swapped out the second one for now.

Let's explore it
Attend Design School to explore a complex problem that you want to solve.

Let's design it
Bring your stakeholders and subject matter experts into the design process in a co-design workshop.
https://federalist-proxy.app.cloud.gov/site/labopm/website/class/custom/co-design-workshop/

Let's build it
Design-led work at the Lab has resulted in programs and tools that improve hiring outcomes.
(Will update this one once we have something on the Featured Work page. Ideally would start it with a verb like the others.)

Let's solve it
Reframe existing problems to spark new solutions.

**Comment by timtimtimtimofficial** [comment]
* "Let's design it" -- That's the perfect spot to call out the co-design workshops! 👍 
* Using the Problem Framing module to illustrate "Let's solve it" at the end rings a little anticlimactic to me, but I'm probably overthinking. "Solve" is a hard thing to exemplify and it's good to have a module linked to from the homepage.
