### ISSUE TITLE
Check class descriptions against course catalog

### ISSUE THREAD

**Issue by jenkack** [labopm/website#9]

**Comment by humancompanion** [comment]
All of the class descriptions were taken from the course catalog. However, two questions:

1. Should the Custom Offering "classes" (there are 4) be added? 
2. Should Design Partnerships be added as a new section of Take a Class? Or somewhere else?

**Comment by jenkack** [comment]
1. Yes, that would be great to include on the Custom Classes page as in the catalog
2. IMO this fits best on the Partner with The Lab page. How about adding Design Partnerships language on that page between the first graph and Our Partners list, then I will edit down from there. @timtimtimtimofficial Does that sound right to you? I like the course catalog language, which was created after the web copy deck.

**Comment by humancompanion** [comment]
@jenkack - Okay, I added the Design Partnerships content. But now we have a very specific list of projects and partners followed by a very long and generic list of partners. We need the language around those to change, in addition to the list edits you wanted to make.

I'll work on the Custom Classes next.

**Comment by jenkack** [comment]
I'm going to separate out the Custom Classes addition into its own issue and close this one, as we'll be doing some separate/additional changes to the Partner page and will track that in another issue as well.
